# Generated by Django 6.0 on 2025-12-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='addres1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='addres2',
            new_name='address2',
        ),
    ]
