# Generated by Django 6.0 on 2025-12-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tree',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
