# Generated by Django 6.0 on 2025-12-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_tree_height_alter_tree_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
