# Generated by Django 6.0 on 2025-12-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tree_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='decorations',
            field=models.ManyToManyField(blank=True, to='products.decoration'),
        ),
    ]
